name: Build and Release

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        env:
            BUILD_VERSION: "0.5.4"

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  ref: v${{ env.BUILD_VERSION }}

            - name: Set up JDK 21
              uses: actions/setup-java@v3
              with:
                  distribution: "temurin"
                  java-version: "21"

            - name: Set up Gradle
              uses: gradle/gradle-build-action@v2

            - name: Build the mod
              run: ./gradlew build

            - name: Create new tag
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "actions@github.com"
                  new_tag="v${{ env.BUILD_VERSION }}-build"
                  git tag $new_tag
                  git push origin $new_tag
            - name: Remove *-dev.jar
              run: rm ./build/libs/*-dev.jar || true
            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "v${{ env.BUILD_VERSION }}-build"
                  prerelease: false
                  title: "Release v${{ env.BUILD_VERSION }}-build"
                  files: |
                      ./build/libs/*.jar          
